version: '3'

services: 
    db:
        #platform: linux/x86_64
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: phuonghai
            MYSQL_DATABASE: phuonghai
            MYSQL_USER: phuonghai
            MYSQL_PASSWORD: phuonghai
        ports: 
            - 3306:3306
