version: '3'

services: 
    db:
  
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        cap_add: 
            - SYS_NICE  # CAP_SYS_NICE
        environment:
            MYSQL_ROOT_PASSWORD: phuonghai
            MYSQL_DATABASE: phuonghaidb
            MYSQL_USER: phuonghai
            MYSQL_PASSWORD: phuonghai
        ports: 
            - 3309:3306
